### ISSUE TITLE
'Upstreaming' your patches

### ISSUE THREAD

**Issue by trevorsandy** [devernay/osmesa-install#6]
Hello Fréderic,

As you may know, building OSMesa on scons/MinGW is quite broken. The problem is in the 'swr' module. 

I am working with George Kyriazis (from Intel) on validating his patch. In this activity, Emil Velikov from Mesa has stressed that it is strongly recommended to 'upstream' the other patches I use to successfully build OSMesa. As I am not the author, I'm not sure how I can help so I'm writing to let you know because, except George's patch, the patches I use come from this repo.

If you are interested, I've made a lot of enhancements to the osmesa-install.sh script to enable fully automated, flexible and detailed building on scons/MinGW. This weekend I completed an AppVeyor CI environment, using the osmesa-install script, to support George's patch build testing. You can see details at [the corresponding Git Repo](https://github.com/trevorsandy/osmesa_mingw_av).

Cheers,

**Comment by devernay** [comment]
Hi Trevor,
feel free to use, distribute and reuse any patch from this repo. I spent time on these so that they may be useful to someone.
There is still work to do on the latest osmesa (17.2.1), for which a thread-safe patch has to b eworked on.

**Comment by trevorsandy** [comment]
Hi Fréderic,
Many thanks.

Cheers,
